spring:
  application:
    name: product-catalog
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    representation:
      uuid: standard
  web:
    locale-resolver: fixed
    locale: en_US

algashop:
  dataloader:
    enabled: false
    auto-delete: false