logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.protocol.query: DEBUG
    org.mongodb.driver.connection: DEBUG

server.port: 8083

spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: algashop
      database: 0
      timeout: 600
  mongodb:
    uri: mongodb://localhost:27017,localhost:27018,localhost:27019/product_catalog?replicaSet=rs0

algashop:
  dataloader:
    enabled: true
    auto-delete: true
    document-locations:
      - location: classpath:data/product_catalog.product-nic-import.json
        collection-name: products
      - location: classpath:data/product_catalog.category-import.json
        collection-name: categories